name: Tdlib Max x64 Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: install homebrew
      run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    - name: Install dependencies via brew
      run: brew install gperf cmake openssl
    - name: Clone tdlib
      run: git clone https://github.com/tdlib/td.git
    - name: Checkout 1.8.0 tag
      working-directory: td
      run: git checkout v1.8.0
    - name: Create release dir
      run: mkdir release
    - name: Create build dir
      working-directory: td
      run: mkdir build
    - name: Run cmake
      working-directory: td/build
      run: cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ -DCMAKE_INSTALL_PREFIX:PATH=../../release -DTD_ENABLE_LTO=ON ..
    - name: Run cmake install
      working-directory: td/build
      run: cmake --build . --target install
    - name: Remove cmake dir
      working-directory: release/lib
      run: rm -rf cmake
    - uses: actions/upload-artifact@master
      with:
          name: Mac x64 Release
          path: release/lib
